theme: jekyll-theme-minimal

# title of the website (displayed in the header)
title: Linxia GONG<br>巩琳霞
# logo picture
logo:
description: Reinforcement Learning Research Engineer, <br> Sea AI Lab, Singapore.

# Owner information
owner_info:
  owner_url: https://linxiagong.github.io/
  linkedin: linxiagong
  github: linxiagong
  google_scholar:
  email: linxiagong@gmail.com
  tel: (+86)152 6701 8587 /(+65) 8885 4929
  twitter:
  instagram:
  zhihu: linxiagong

# Resume file path
resume:
  en:
  cn: 
  # ./myResumes/巩琳霞_用户画像研究员.pdf